### ISSUE TITLE
Separate script brushmodels into a different .obj?

### ISSUE THREAD

**Issue by ficool2** [Scobalula/Husky#3]
Not sure if this is possible, but it would be nice if it was possible to separate all the script brushmodels into their own .obj, since its an absolute pain to try separate them from the map geometry
The game I'm ripping from is COD: Black Ops 1

On a sidenote: would it be possible to get basic primary light entity dumps soon? They are viewable ingame with the r_showprimarylights command (shows origin + angles + light color)

**Comment by Scobalula** [comment]
I'm not looking into anymore data, this was really just a pet project to dump geo, if people want to extend it the source code is there to do so.
